### PR TITLE
Update to the parameters output PR

### PR DESCRIPTION
**Pull request by zhubonan**
**Please check the applicable boxes, thank you**:

I, the author consider this PR
 - [x] ready to be reviewed and merged (as soon as tests have passed)
 - [ ] work in progress (early feedback welcome)

## Interactions with issues / other PRs

*type "#" followed by search words to find issues / PRs*

fixes:

blocks:

is blocked by:

None of the above but is still related to the following:

## Description

Hello I just did a minor update to move the parameters output to the `misc` node and make it default to false. We kind of try to limit the number of nodes each calculation produce. Is it OK for your use case?

To turn on recording of the exact parameters used, set `builder.settings['paraser_settings']['include_quantitity'] = ['parameters']`

### CODE REVIEW

**Comment by zhubonan** [comment]
@nkeilbart Please let me know what you think! I am keen to get the aiida-vasp PR merged soon: https://github.com/aiida-vasp/aiida-vasp/pull/745

**Review by nkeilbart — APPROVED** [review]
Sorry I've been busy with some personal life things and haven't had a chance to look at this. I did a general read and it seems good.

**Comment by nkeilbart** [comment]
Let me know if I need to do anything else on my end.

**Comment by zhubonan** [comment]
No worries. Sorry I missed the  GitHub notification... 

If you merge it then i can merge the PR to the aiida-vasp's repo. Thanks a lot for this.

**Comment by nkeilbart** [comment]
@zhubonan I think I merged it. Doing everything on my phone so hopefully I did it right.

**Pull request merged**
